# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# TUI VISUAL CLIENT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

client_id = "d420a117a32841c2b3474932e49fb54b"
client_port = 8989 # Must match the daemon
theme = "Blue whale"

# Disable Backend Overlaps
enable_streaming = "DaemonOnly"
enable_media_control = false 
enable_notify = false

# Minimalist Aesthetics
border_type = "Rounded"
progress_bar_type = "Line" 
progress_bar_position = "Right"
play_icon = "⏵" # Modern unicode
pause_icon = "⏸"
liked_icon = "" # FontAwesome heart (assuming a Nerd Font)
explicit_icon = "🅴"

playback_format = """
{status} {track} {liked}



{artists}



{album} (Track {track_number})



{genres}



{metadata}"""

# The Showcase Image (Kitty Graphics Protocol)
# 36 columns x 18 rows = perfect 2:1 aspect ratio square for terminal cells
cover_img_length = 36
cover_img_width = 18
cover_img_scale = 1.0
enable_cover_image_cache = true

# Layout Tuning
[layout]
playback_window_position = "Top" 
playback_window_height = 20 # 18 rows for image + 2 rows for padding
