general {
	gaps_in = 4
	gaps_out = 8
	border_size = 1
	col.active_border = rgba(303030ee)
	col.inactive_border = rgba(0f0f0fee)
	layout = dwindle
	allow_tearing = false
}

	drop_shadow = false
decoration {
	rounding = 4
	blur {
		enabled = true
		size = 3
		passes = 2
		new_optimizations = true
		ignore_opacity = true
	}
}

decoration:shadow {
	enabled = true
	range = 8
	render_power = 3
	color = rgba(000000aa)
}


animations {
	enabled = true
	bezier = fluent, 0.05, 0.9, 0.1, 1.0
	animation = windows, 1, 3, fluent, slide
	animation = border, 1, 5, default
	animation = fade, 1, 3, default
	animation = workspaces, 1, 4, default
}

gesture = 3, horizontal, workspace
